"""Unit tests for Round 51 — 读侧 core properties 回读。"""

from __future__ import annotations

import pytest
from docx import Document
from openpyxl import Workbook

from backend.office.excel import generate_xlsx, read_xlsx
from backend.office.models import (
    ExcelSheetSpec,
    OfficeExcelGenerateRequest,
    OfficeWordGenerateRequest,
    WordMetadataSpec,
    WordParagraphSpec,
    WordTableSpec,
)
from backend.office.word import generate_docx, read_docx

pytestmark = pytest.mark.unit


def test_docx_metadata_roundtrip(tmp_path) -> None:
    output = generate_docx(
        OfficeWordGenerateRequest(
            workspace_path="",
            filename="r.docx",
            title="季度报告",
            paragraphs=[WordParagraphSpec(text="正文")],
            tables=[WordTableSpec(headers=["A"], rows=[["1"]])],
            metadata=WordMetadataSpec(author="张三", keywords="营收；成本"),
        ),
        output_dir=str(tmp_path),
    )
    result = read_docx(output, workspace_path="")
    assert result.metadata is not None
    assert result.metadata.author == "张三"
    assert result.metadata.keywords == "营收；成本"


def test_docx_read_without_metadata_returns_none(tmp_path) -> None:
    output = generate_docx(
        OfficeWordGenerateRequest(
            workspace_path="",
            filename="plain.docx",
            title="报告",
            paragraphs=[WordParagraphSpec(text="正文")],
            tables=[WordTableSpec(headers=["A"], rows=[["1"]])],
        ),
        output_dir=str(tmp_path),
    )
    # 模板自带默认（python-docx/generated by python-docx）——显式清空后
    # 读侧才应返回 None。
    doc = Document(str(output))
    core = doc.core_properties
    core.author = ""
    core.comments = ""
    doc.save(str(output))
    result = read_docx(output, workspace_path="")
    assert result.metadata is None


def test_xlsx_metadata_roundtrip(tmp_path) -> None:
    output = generate_xlsx(
        OfficeExcelGenerateRequest(
            workspace_path="",
            filename="t.xlsx",
            sheets=[ExcelSheetSpec(name="数据", headers=["A"], rows=[["1"]])],
            metadata=WordMetadataSpec(author="李四", subject="台账"),
        ),
        output_dir=str(tmp_path),
    )
    result = read_xlsx(output, workspace_path="")
    assert result.metadata is not None
    assert result.metadata.author == "李四"
    assert result.metadata.subject == "台账"


def test_xlsx_read_without_metadata_returns_none(tmp_path) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "数据"
    ws["A1"] = "x"
    path = tmp_path / "plain.xlsx"
    wb.save(str(path))
    # 模板自带默认 author=openpyxl——显式清空后读侧才应返回 None。
    wb2 = Workbook()
    ws2 = wb2.active
    ws2.title = "数据"
    ws2["A1"] = "x"
    wb2.properties.creator = ""
    path2 = tmp_path / "blank.xlsx"
    wb2.save(str(path2))
    result = read_xlsx(path2, workspace_path="")
    assert result.metadata is None
