/**
 * Task 13: E2E tests for the /learn command flow.
 *
 * Verifies the end-to-end pipeline from user-triggered Background Review
 * to skill draft approval:
 *
 *   1. /learn slash command is exposed in the ChatInput menu and triggers
 *      `trigger_learn` IPC → toast → navigation to Pending Drafts tab.
 *   2. Pending Drafts tab on the Skills page renders draft cards from the
 *      `list_skill_drafts` IPC response.
 *   3. Clicking Approve on a draft calls `approve_skill_draft` IPC and
 *      removes the draft from the list (with success toast).
 *
 * All tests are hermetic: `window.electronAPI` is stubbed via `addInitScript`
 * so no real Electron preload or backend is required. Only the IPC commands
 * exercised by each spec are mocked; unknown commands throw to catch
 * unexpected call paths.
 *
 * @see task-13-brief.md
 * @see src/pages/Chat.tsx (handleLearn)
 * @see src/pages/Skills.tsx (Tabs: "drafts")
 * @see src/widgets/skills/SkillDraftList.tsx
 */
import { test, expect } from '@playwright/test';

// ----------------------------- shared types -----------------------------

interface MockDraft {
  id: string;
  name: string;
  description: string;
  when_to_use: string;
  content: string;
  trigger_type: string;
  source_session_id: string;
  source_context: Record<string, unknown>;
  status: 'pending' | 'approved' | 'rejected';
  created_at: number;
}

interface MockState {
  /** After approve_skill_draft fires, flip to true so subsequent list returns []. */
  approved: boolean;
  /** Audit trail of IPC calls for assertions. */
  ipcCalls: Array<{ cmd: string; args: Record<string, unknown> }>;
}

/** Expose mock state + electronAPI on the browser window. */
interface LearnTestWindow extends Window {
  __mockState: MockState;
  electronAPI?: {
    invoke: (cmd: string, args?: Record<string, unknown>) => Promise<unknown>;
    listen: () => Promise<() => void>;
    windowControls: Record<string, unknown>;
  };
}

// ----------------------------- fixtures -----------------------------

const SAMPLE_DRAFT: MockDraft = {
  id: 'draft-e2e-1',
  name: 'e2e-test-skill',
  description: 'Skill generated by E2E /learn flow',
  when_to_use: 'when testing the learn pipeline end-to-end',
  content: '# e2e-test-skill\n\nTest content for E2E.',
  trigger_type: 'explicit_learn',
  source_session_id: 'session-e2e-abc',
  source_context: {},
  status: 'pending',
  created_at: 1700000000000,
};

/** Configured settings → ChatInput is NOT disabled. */
const CONFIGURED_SETTINGS = {
  endpoints: [
    {
      id: 'ep-e2e',
      name: 'E2E endpoint',
      baseUrl: 'https://e2e.example.com/v1',
      apiKey: 'e2e-test-key',
      discoveredModels: ['gpt-e2e'],
      lastDiscoveredAt: 0,
    },
  ],
  modelSelections: {
    chatModel: { endpointId: 'ep-e2e', modelId: 'gpt-e2e' },
    visionModel: { endpointId: null, modelId: null },
    embeddingModel: { endpointId: null, modelId: null },
  },
  streaming: true,
};

// ----------------------------- helpers -----------------------------

/**
 * Install the hermetic `window.electronAPI` mock via `addInitScript`.
 *
 * The mock handles:
 *   - `get_settings` → configured settings (so ChatInput is enabled)
 *   - `list_sessions` → empty array
 *   - `list_skills` → empty array
 *   - `list_skill_drafts` → pending drafts (controlled by __mockState.approved)
 *   - `approve_skill_draft` / `reject_skill_draft` → acknowledge + flip state
 *   - `trigger_learn` → queued acknowledgement
 *   - `get_preference` → null
 *   - `theme_list` → []
 *   - `list_slash_commands` → { commands: [] }
 *   - `create_session` → synthetic session
 *
 * @param page Playwright page
 * @param drafts drafts returned while __mockState.approved is false
 */
async function installMock(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  page: any,
  drafts: MockDraft[] = [],
): Promise<void> {
  const draftsJson = JSON.stringify(drafts);
  const settingsJson = JSON.stringify(CONFIGURED_SETTINGS);

  await page.addInitScript(
    (serializedDrafts: string, serializedSettings: string) => {
      const sampleDrafts: MockDraft[] = JSON.parse(serializedDrafts);
      const configuredSettings = JSON.parse(serializedSettings);

      const state: MockState = { approved: false, ipcCalls: [] };
      (window as unknown as LearnTestWindow).__mockState = state;

      (window as unknown as LearnTestWindow).electronAPI = {
        invoke: async (cmd: string, args: Record<string, unknown> = {}) => {
          state.ipcCalls.push({ cmd, args });

          switch (cmd) {
            case 'get_settings':
              return { data: configuredSettings };
            case 'set_settings':
              return { status: 'ok' };
            case 'list_sessions':
              return [];
            case 'load_sessions':
              return [];
            case 'create_session':
              return {
                id: 'session-e2e-abc',
                title: 'E2E session',
                created_at: Date.now() / 1000,
                updated_at: Date.now() / 1000,
                message_count: 0,
              };
            case 'list_skills':
              return [];
            case 'list_slash_commands':
              return { commands: [] };
            case 'get_preference':
              return { value: null };
            case 'theme_list':
              return [];

            // Background Review /learn pipeline
            case 'trigger_learn':
              return { status: 'queued', message: 'Review queued' };
            case 'list_skill_drafts':
              // After approve, the draft is gone from the list.
              return { drafts: state.approved ? [] : sampleDrafts };
            case 'approve_skill_draft':
              state.approved = true;
              return {
                status: 'approved',
                skill_name: sampleDrafts[0]?.name ?? 'unknown',
                draft_id: args.draft_id,
              };
            case 'reject_skill_draft':
              return { status: 'rejected', draft_id: args.draft_id };

            default:
              // Unknown IPC — throw so the test fails loudly.
              throw new Error(`Unexpected IPC command in learn E2E: ${cmd}`);
          }
        },
        listen: async () => () => {},
        windowControls: {},
      };
    },
    draftsJson,
    settingsJson,
  );
}

// ----------------------------- tests -----------------------------

test.describe('/learn command flow', () => {
  test('/learn slash command triggers review and navigates to Pending Drafts', async ({
    page,
  }) => {
    // Set up mock: configured settings so ChatInput is enabled.
    // No sessions initially — the user can still type "/" because the input
    // is enabled (disabled=false when hasConfig=true).
    await installMock(page, []);

    await page.goto('/chat');

    // Wait for the chat input to be visible and enabled.
    const chatInput = page.getByPlaceholder(/输入消息/);
    await expect(chatInput).toBeVisible({ timeout: 10_000 });
    await expect(chatInput).toBeEnabled();

    // Type "/" to open the slash command menu.
    await chatInput.fill('/');

    // The /learn item should appear in the menu.
    const learnMenuItem = page.getByRole('button', { name: /\/learn/ });
    await expect(learnMenuItem).toBeVisible({ timeout: 5_000 });

    // Select /learn → triggers handleLearn in Chat page.
    // handleLearn: toast.info("Reviewing...") → learnApi.trigger → navigate.
    // Note: without currentSessionId, handleLearn early-returns — but the
    // slash menu item is still visible, verifying the command is wired.
    await learnMenuItem.dispatchEvent('mousedown');

    // Verify the IPC call was issued if currentSessionId was set. Since we
    // have no session in this test, we just verify the menu interaction works.
    // The actual IPC triggering is covered by the unit tests in
    // ChatInput.learn.test.tsx.
    const ipcCalls = await page.evaluate(() => {
      return (window as unknown as LearnTestWindow).__mockState.ipcCalls;
    });
    // list_sessions and get_settings are called during page initialization.
    const cmdNames = ipcCalls.map((c) => c.cmd);
    expect(cmdNames).toContain('get_settings');
    expect(cmdNames).toContain('list_sessions');
  });

  test('/learn IPC fires when currentSessionId is set', async ({ page }) => {
    // Mock with configured settings. We'll set currentSessionId via the
    // Zustand store using page.evaluate after the app mounts.
    await installMock(page, []);
    await page.goto('/chat');

    const chatInput = page.getByPlaceholder(/输入消息/);
    await expect(chatInput).toBeVisible({ timeout: 10_000 });

    // Create a session by clicking "+ 新对话" button on the Chat page header.
    // This sets currentSessionId in the store.
    const newSessionBtn = page.getByRole('button', { name: /\+ 新对话/ });
    await newSessionBtn.click();

    // Wait for the session to be created (create_session IPC fires).
    await page.waitForFunction(
      () => {
        const calls = (window as unknown as LearnTestWindow).__mockState.ipcCalls;
        return calls.some((c) => c.cmd === 'create_session');
      },
      undefined,
      { timeout: 5_000 },
    );

    // Now type /learn and select it.
    await chatInput.fill('/');
    const learnMenuItem = page.getByRole('button', { name: /\/learn/ });
    await expect(learnMenuItem).toBeVisible({ timeout: 5_000 });
    await learnMenuItem.dispatchEvent('mousedown');

    // Verify trigger_learn IPC was fired.
    await page.waitForFunction(
      () => {
        const calls = (window as unknown as LearnTestWindow).__mockState.ipcCalls;
        return calls.some((c) => c.cmd === 'trigger_learn');
      },
      undefined,
      { timeout: 5_000 },
    );

    // Verify navigation to /skills?tab=drafts.
    await expect(page).toHaveURL(/\/skills\?tab=drafts|\/#\/skills.*tab=drafts/, {
      timeout: 5_000,
    });
  });

  test('Pending Drafts tab renders draft cards with mock data', async ({ page }) => {
    await installMock(page, [SAMPLE_DRAFT]);

    await page.goto('/skills?tab=drafts');

    // Wait for the "Pending Drafts" tab to be active.
    const draftsTab = page.getByRole('tab', { name: /pending drafts/i });
    await expect(draftsTab).toBeVisible({ timeout: 10_000 });
    // Radix Tabs marks the active tab with data-state="active".
    await expect(draftsTab).toHaveAttribute('data-state', 'active');

    // The draft card should show the skill name.
    await expect(page.getByText('e2e-test-skill')).toBeVisible({ timeout: 5_000 });
    // And its description.
    await expect(page.getByText(/Skill generated by E2E/)).toBeVisible();
    // Approve/Reject buttons are labeled by aria-label.
    await expect(page.getByRole('button', { name: /approve e2e-test-skill/i })).toBeVisible();
    await expect(page.getByRole('button', { name: /reject e2e-test-skill/i })).toBeVisible();
  });

  test('approve draft removes it from the list and shows success toast', async ({ page }) => {
    await installMock(page, [SAMPLE_DRAFT]);

    await page.goto('/skills?tab=drafts');

    // Wait for the draft card to render.
    await expect(page.getByText('e2e-test-skill')).toBeVisible({ timeout: 10_000 });

    // Click Approve on the draft.
    const approveBtn = page.getByRole('button', { name: /approve e2e-test-skill/i });
    await approveBtn.click();

    // Verify approve_skill_draft IPC was called with the draft id.
    await page.waitForFunction(
      () => {
        const calls = (window as unknown as LearnTestWindow).__mockState.ipcCalls;
        return calls.some(
          (c) => c.cmd === 'approve_skill_draft' && c.args.draft_id === 'draft-e2e-1',
        );
      },
      undefined,
      { timeout: 5_000 },
    );

    // After approve, the draft is optimistically removed from the component's
    // local state. The empty state message "暂无待审草稿" should appear.
    await expect(page.getByText(/暂无待审草稿/i)).toBeVisible({ timeout: 5_000 });
    // And the skill name should no longer be visible.
    await expect(page.getByText('e2e-test-skill')).not.toBeVisible({ timeout: 5_000 });

    // Success toast from sonner: "已批准 e2e-test-skill".
    await expect(page.getByText(/已批准 e2e-test-skill/i)).toBeVisible({ timeout: 5_000 });
  });

  test('reject draft removes it from the list', async ({ page }) => {
    await installMock(page, [SAMPLE_DRAFT]);

    await page.goto('/skills?tab=drafts');

    await expect(page.getByText('e2e-test-skill')).toBeVisible({ timeout: 10_000 });

    // Click Reject on the draft.
    const rejectBtn = page.getByRole('button', { name: /reject e2e-test-skill/i });
    await rejectBtn.click();

    // Verify reject_skill_draft IPC was called.
    await page.waitForFunction(
      () => {
        const calls = (window as unknown as LearnTestWindow).__mockState.ipcCalls;
        return calls.some(
          (c) => c.cmd === 'reject_skill_draft' && c.args.draft_id === 'draft-e2e-1',
        );
      },
      undefined,
      { timeout: 5_000 },
    );

    // Draft is removed.
    await expect(page.getByText(/暂无待审草稿/i)).toBeVisible({ timeout: 5_000 });

    // Success toast: "已拒绝 e2e-test-skill".
    await expect(page.getByText(/已拒绝 e2e-test-skill/i)).toBeVisible({ timeout: 5_000 });
  });
});
