"""Unit tests for ``backend.zotero.client.ZoteroClient``.

Uses the synthetic fixture at ``backend/tests/fixtures/zotero.sqlite``
generated by ``backend.tests.fixtures.generate_zotero_fixture``.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from backend.zotero import ZoteroClient
from backend.zotero.exceptions import (
    ZoteroCollectionNotFoundError,
    ZoteroItemNotFoundError,
)

FIXTURE_PATH = (
    Path(__file__).resolve().parents[1] / "fixtures" / "zotero.sqlite"
)


@pytest.fixture()
def client() -> ZoteroClient:
    """Return a ZoteroClient pointed at the synthetic fixture."""
    if not FIXTURE_PATH.exists():
        from backend.tests.fixtures.generate_zotero_fixture import build_fixture

        build_fixture(FIXTURE_PATH)
    return ZoteroClient(db_path=FIXTURE_PATH)


class TestHealthAndStats:
    """Health check and library statistics."""

    def test_health_check_returns_ok(self, client: ZoteroClient) -> None:
        health = client.health_check()
        assert health["status"] == "ok"
        assert health["item_count"] == 5

    def test_get_stats_returns_counts(self, client: ZoteroClient) -> None:
        stats = client.get_stats()
        assert stats["items"] == 5
        assert stats["collections"] == 5
        assert stats["tags"] == 3
        assert stats["attachments"] == 3


class TestSearch:
    """Search by title/abstract/author."""

    def test_search_by_title(self, client: ZoteroClient) -> None:
        results = client.search("Transformer")
        assert len(results) >= 1
        assert any("Transformer" in r["title"] for r in results)

    def test_search_by_author_last_name(self, client: ZoteroClient) -> None:
        results = client.search("Doe")
        assert len(results) >= 1
        assert any("Doe" in r["authors"] for r in results)

    def test_search_by_abstract(self, client: ZoteroClient) -> None:
        results = client.search("comprehensive survey")
        assert any("Neural Network" in r["title"] for r in results)

    def test_search_filters_by_collection(self, client: ZoteroClient) -> None:
        results = client.search("Neural", collection_key="COLL001")
        assert len(results) >= 1

    def test_search_filters_by_tag(self, client: ZoteroClient) -> None:
        results = client.search("Neural", tag="machine-learning")
        assert len(results) >= 1

    def test_search_respects_limit(self, client: ZoteroClient) -> None:
        results = client.search("paper", limit=2)
        assert len(results) <= 2

    def test_search_no_match_returns_empty(self, client: ZoteroClient) -> None:
        results = client.search("QuantumGravity")
        assert results == []


class TestGetItem:
    """Full metadata retrieval."""

    def test_get_item_returns_full_metadata(self, client: ZoteroClient) -> None:
        item = client.get_item("ABCD1234")
        assert item["key"] == "ABCD1234"
        assert item["title"] == "Neural Network Survey Paper"
        assert item["doi"] == "10.1234/jmlr.2024.001"
        assert item["item_type"] == "journalArticle"
        assert len(item["authors"]) == 2
        assert len(item["tags"]) == 2

    def test_get_item_authors_ordered(self, client: ZoteroClient) -> None:
        item = client.get_item("ABCD1234")
        # First author by orderIndex=0
        assert item["authors"][0]["lastName"] == "Doe"
        assert item["authors"][1]["lastName"] == "Smith"

    def test_get_item_includes_attachments(self, client: ZoteroClient) -> None:
        item = client.get_item("ABCD1234")
        assert len(item["attachments"]) == 1
        assert item["attachments"][0]["contentType"] == "application/pdf"

    def test_get_item_includes_collections(self, client: ZoteroClient) -> None:
        item = client.get_item("ABCD1234")
        keys = [c["key"] for c in item["collections"]]
        assert "COLL001" in keys
        assert "COLL002" in keys

    def test_get_item_includes_notes(self, client: ZoteroClient) -> None:
        item = client.get_item("ABCD1234")
        assert len(item["notes"]) == 1
        assert "p. 5" in item["notes"][0]["note"]

    def test_get_item_unknown_key_raises(self, client: ZoteroClient) -> None:
        with pytest.raises(ZoteroItemNotFoundError):
            client.get_item("DOESNOTEXIST")


class TestAnnotations:
    """PDF annotation retrieval."""

    def test_get_annotations_returns_pdf_annotations(self, client: ZoteroClient) -> None:
        annotations = client.get_annotations("ABCD1234")
        assert len(annotations) == 2

    def test_get_annotations_contains_highlight_text(self, client: ZoteroClient) -> None:
        annotations = client.get_annotations("ABCD1234")
        highlight = next(a for a in annotations if a["type"] == "highlight")
        assert "state of the art" in highlight["text"]
        assert highlight["pageLabel"] == "3"

    def test_get_annotations_contains_color(self, client: ZoteroClient) -> None:
        annotations = client.get_annotations("ABCD1234")
        highlight = next(a for a in annotations if a["type"] == "highlight")
        assert highlight["color"] == "#ff0000"

    def test_get_annotations_item_without_pdf_returns_empty(
        self, client: ZoteroClient
    ) -> None:
        annotations = client.get_annotations("THES0001")
        assert annotations == []


class TestCollections:
    """Collection listing."""

    def test_list_top_level_collections(self, client: ZoteroClient) -> None:
        collections = client.list_collections()
        names = [c["name"] for c in collections]
        assert "NLP Papers" in names
        assert "Books" in names
        assert "Transformer Models" not in names

    def test_list_child_collections(self, client: ZoteroClient) -> None:
        children = client.list_collections(parent_key="COLL001")
        assert len(children) == 1
        assert children[0]["name"] == "Transformer Models"
        assert children[0]["parentKey"] == "COLL001"

    def test_list_collection_includes_item_count(self, client: ZoteroClient) -> None:
        collections = client.list_collections()
        nlp = next(c for c in collections if c["key"] == "COLL001")
        assert nlp["itemCount"] == 2

    def test_list_unknown_parent_raises(self, client: ZoteroClient) -> None:
        with pytest.raises(ZoteroCollectionNotFoundError):
            client.list_collections(parent_key="DOESNOTEXIST")


class TestBibTeX:
    """BibTeX export."""

    def test_get_bibtex_single_item(self, client: ZoteroClient) -> None:
        bibtex = client.get_bibtex(["ABCD1234"])
        assert "@article{ABCD1234," in bibtex
        assert "title = {Neural Network Survey Paper}" in bibtex
        assert "Doe, Jane" in bibtex
        assert "Smith, John" in bibtex

    def test_get_bibtex_multiple_items(self, client: ZoteroClient) -> None:
        bibtex = client.get_bibtex(["ABCD1234", "BOOK0001"])
        assert "@article{ABCD1234," in bibtex
        assert "@book{BOOK0001," in bibtex

    def test_get_bibtex_book_maps_to_book_entry(self, client: ZoteroClient) -> None:
        bibtex = client.get_bibtex(["BOOK0001"])
        assert "@book{BOOK0001," in bibtex

    def test_get_bibtex_unknown_item_raises(self, client: ZoteroClient) -> None:
        with pytest.raises(ZoteroItemNotFoundError):
            client.get_bibtex(["DOESNOTEXIST"])


class TestReadPdfFulltext:
    """PDF full-text reading."""

    def test_read_pdf_returns_indexed_text(self, client: ZoteroClient) -> None:
        result = client.read_pdf_fulltext("ABCD1234")
        assert result["source"] == "index"
        assert "neural" in result["chunk_text"]
        assert "model" in result["chunk_text"]

    def test_read_pdf_reports_total_chars(self, client: ZoteroClient) -> None:
        result = client.read_pdf_fulltext("ABCD1234")
        assert result["total_chars"] > 0

    def test_read_pdf_chunks_at_offset(self, client: ZoteroClient) -> None:
        first = client.read_pdf_fulltext("ABCD1234", chunk_offset=0)
        result = client.read_pdf_fulltext("ABCD1234", chunk_offset=5)
        assert result["chunk_offset"] == 5
        # chunk_offset indicates where reading starts in the full text
        assert result["chunk_text"] == first["chunk_text"][5:]

    def test_read_pdf_reports_unavailable_for_unindexed(
        self, client: ZoteroClient
    ) -> None:
        result = client.read_pdf_fulltext("BOOK0001")
        assert result["source"] in ("file", "unavailable")

    def test_read_pdf_unknown_item_raises(self, client: ZoteroClient) -> None:
        with pytest.raises(ZoteroItemNotFoundError):
            client.read_pdf_fulltext("DOESNOTEXIST")


class TestExceptions:
    """Exception classes (smoke tests)."""

    def test_item_not_found_message_contains_key(self) -> None:
        exc = ZoteroItemNotFoundError("ABC123")
        assert "ABC123" in str(exc)

    def test_collection_not_found_message_contains_key(self) -> None:
        exc = ZoteroCollectionNotFoundError("COLL999")
        assert "COLL999" in str(exc)
