/**
 * 设置元数据注册表。
 *
 * 元数据统一描述设置的存储位置、默认值、可见性、风险和生效时机。
 */

import type { SettingMetadata } from './metadata';
import { DEFAULT_SETTINGS } from './types';

const booleanSetting = (
  key: string,
  label: string,
  description: string,
  storage: SettingMetadata['storage'],
  defaultValue: boolean,
  applyMode: SettingMetadata['applyMode'] = 'immediate',
  visibility: SettingMetadata['visibility'] = 'basic',
): SettingMetadata => ({
  key,
  label,
  description,
  scope: 'global',
  storage,
  defaultValue,
  applyMode,
  visibility,
  riskLevel: 'low',
  constraints: { type: 'boolean' },
});

const numberSetting = (
  key: string,
  label: string,
  description: string,
  storage: SettingMetadata['storage'],
  defaultValue: number,
  min: number,
  max?: number,
  applyMode: SettingMetadata['applyMode'] = 'next-request',
  visibility: SettingMetadata['visibility'] = 'advanced',
): SettingMetadata => ({
  key,
  label,
  description,
  scope: 'global',
  storage,
  defaultValue,
  applyMode,
  visibility,
  riskLevel: 'medium',
  constraints: { type: 'number', min, ...(max === undefined ? {} : { max }) },
});

const enumSetting = (
  key: string,
  label: string,
  description: string,
  storage: SettingMetadata['storage'],
  defaultValue: string,
  options: Array<{ value: string; label: string }>,
  applyMode: SettingMetadata['applyMode'] = 'immediate',
  visibility: SettingMetadata['visibility'] = 'basic',
): SettingMetadata => ({
  key,
  label,
  description,
  scope: 'global',
  storage,
  defaultValue,
  applyMode,
  visibility,
  riskLevel: 'low',
  constraints: { type: 'enum', options },
});

const orchNumber = (
  key: string,
  label: string,
  description: string,
  defaultValue: number,
  min: number,
  max?: number,
): SettingMetadata => ({
  ...numberSetting(key, label, description, 'app_settings', defaultValue, min, max, 'next-run'),
  storageKey: key,
});

export const settingsRegistry: Record<string, SettingMetadata> = {
  streaming: booleanSetting(
    'streaming',
    '流式输出',
    '逐字显示 AI 回复，而非等待全部生成完成',
    'app_settings',
    true,
  ),
  autoMemory: booleanSetting(
    'autoMemory',
    '自动记忆提取',
    '对话中自动识别并保存关键信息到记忆库',
    'app_settings',
    true,
  ),
  confirmDelete: booleanSetting(
    'confirmDelete',
    '确认后再删除记忆',
    '删除记忆前弹出确认对话框',
    'app_settings',
    true,
  ),
  maxContext: {
    ...numberSetting(
      'maxContext',
      '上下文窗口',
      '自动模式按模型目录选择；手动模式使用此固定 token 数',
      'app_settings',
      4096,
      256,
      128000,
      'next-request',
      'basic',
    ),
    riskLevel: 'medium',
    dependsOn: ['autoContext'],
  },
  autoContext: {
    ...booleanSetting(
      'autoContext',
      '自动推断上下文窗口',
      '根据模型目录自动选择上下文窗口；关闭时使用固定值',
      'app_settings',
      true,
      'next-request',
    ),
    affects: ['maxContext'],
  },
  temperature: numberSetting(
    'temperature',
    'Temperature',
    '数值越高输出越随机；0 通常最稳定，2 最随机',
    'app_settings',
    0.7,
    0,
    2,
    'next-request',
    'basic',
  ),
  timezone: {
    key: 'timezone',
    label: 'IANA 时区',
    description: '后端使用的时区；默认取系统时区，非法值会被拒绝',
    scope: 'global',
    storage: 'app_settings',
    defaultValue: DEFAULT_SETTINGS.timezone,
    applyMode: 'next-request',
    visibility: 'basic',
    riskLevel: 'low',
    constraints: { type: 'string' },
  },
  logTimezone: {
    key: 'logTimezone',
    label: '日志时区',
    description: '日志时间戳使用 UTC、本地时区或指定 IANA 时区',
    scope: 'global',
    storage: 'app_settings',
    defaultValue: 'UTC',
    applyMode: 'immediate',
    visibility: 'basic',
    riskLevel: 'low',
    constraints: { type: 'string' },
  },
  permission_mode: {
    ...enumSetting(
      'permission_mode',
      '权限模式',
      '控制工具执行时的权限要求',
      'preference',
      'workspace_write',
      [
        { value: 'read_only', label: '只读' },
        { value: 'workspace_write', label: '工作区写入' },
        { value: 'prompt', label: '逐次审批' },
        { value: 'full_access', label: '完全访问' },
      ],
    ),
    riskLevel: 'high',
  },
  network_policy: {
    key: 'network_policy',
    label: '网络模式',
    description: '控制网络工具访问范围；online、intranet 或 offline',
    scope: 'global',
    storage: 'preference',
    defaultValue: { mode: 'online', allowed_hosts: [], insecure_tls_hosts: [] },
    applyMode: 'immediate',
    visibility: 'basic',
    riskLevel: 'high',
    constraints: { type: 'json' },
  },
  web_proxy: {
    key: 'web_proxy',
    label: '抓取代理',
    description: 'HTTP/HTTPS/SOCKS5 代理地址；留空表示不启用',
    scope: 'global',
    storage: 'preference',
    defaultValue: { http: '', https: '' },
    applyMode: 'immediate',
    visibility: 'basic',
    riskLevel: 'low',
    constraints: { type: 'json' },
  },
  search_config: {
    key: 'search_config',
    label: '搜索引擎',
    description: '搜索引擎优先级和 API Key',
    scope: 'global',
    storage: 'preference',
    defaultValue: { order: ['bing', 'ddg'], tavily_key: '', zhipu_key: '' },
    applyMode: 'immediate',
    visibility: 'basic',
    riskLevel: 'low',
    constraints: { type: 'json' },
  },
  embedding_mode: enumSetting(
    'embedding_mode',
    '嵌入器模式',
    'hash 为字面匹配；onnx 为本地语义模型，需要下载模型',
    'preference',
    'hash',
    [
      { value: 'hash', label: '字面匹配' },
      { value: 'onnx', label: '本地语义嵌入' },
    ],
    'next-request',
  ),
  context_turn_limit: numberSetting(
    'context_turn_limit',
    '上下文轮数限制',
    '限制发送给模型的对话轮数；0 表示不限制',
    'preference',
    0,
    0,
    undefined,
    'next-request',
    'basic',
  ),
  auto_topic_detection: booleanSetting(
    'auto_topic_detection',
    '自动话题检测',
    '自动检测对话中的话题变化',
    'preference',
    true,
    'next-request',
    'advanced',
  ),
  topic_detection_threshold: numberSetting(
    'topic_detection_threshold',
    '话题检测敏感度',
    '话题检测阈值，越低越敏感',
    'preference',
    0.5,
    0,
    1,
    'next-request',
    'advanced',
  ),
  compact_threshold_tokens: numberSetting(
    'compact_threshold_tokens',
    '上下文压缩阈值',
    '超过此 token 数时自动压缩上下文；环境变量优先',
    'preference',
    6000,
    1000,
    undefined,
    'next-request',
    'advanced',
  ),
  auto_checkpoint: booleanSetting(
    'auto_checkpoint',
    '发送前自动快照',
    '每轮对话开始前为绑定工作区创建检查点',
    'preference',
    true,
  ),
  spend_limit_usd: numberSetting(
    'spend_limit_usd',
    '每日花费限额 (USD)',
    '按估算成本拦截当日请求；0 表示不限',
    'preference',
    0,
    0,
    undefined,
    'next-request',
    'basic',
  ),
  bash_config: {
    key: 'bash_config',
    label: 'Bash 工具配置',
    description: 'Bash 工具的超时、输出截断和后台会话上限',
    scope: 'global',
    storage: 'preference',
    defaultValue: { timeout_default: 120, timeout_max: 600, output_cap: 30720, max_sessions: 32 },
    applyMode: 'next-request',
    visibility: 'advanced',
    riskLevel: 'medium',
    constraints: { type: 'json' },
  },
  hooks: {
    key: 'hooks',
    label: '钩子',
    description: '工具执行前后的自定义钩子脚本',
    scope: 'global',
    storage: 'preference',
    defaultValue: [],
    applyMode: 'immediate',
    visibility: 'advanced',
    riskLevel: 'medium',
    constraints: { type: 'json' },
  },

  'orch.planPreflightEnabled': {
    key: 'orch.planPreflightEnabled',
    label: '拆解前澄清需求',
    description: '复杂任务编排前先判断目标是否有歧义',
    scope: 'global',
    storage: 'app_settings',
    storageKey: 'orch.planPreflightEnabled',
    defaultValue: true,
    applyMode: 'next-run',
    visibility: 'basic',
    riskLevel: 'low',
    constraints: { type: 'boolean' },
  },
  'orch.planScoutEnabled': {
    key: 'orch.planScoutEnabled',
    label: '拆解前事实侦察',
    description: '拆解前派只读子代理收集事实',
    scope: 'global',
    storage: 'app_settings',
    storageKey: 'orch.planScoutEnabled',
    defaultValue: true,
    applyMode: 'next-run',
    visibility: 'advanced',
    riskLevel: 'low',
    constraints: { type: 'boolean' },
  },
  'orch.maxConcurrentSubagents': {
    ...orchNumber('orch.maxConcurrentSubagents', '最大并发子任务数', '同时运行的子任务数量，必须大于 0', 4, 1, 100),
    validate: (value) => (typeof value === 'number' && value >= 1 ? null : '并发数必须大于 0'),
    visibility: 'basic',
  },
  'orch.maxRetries': orchNumber('orch.maxRetries', '子任务重试次数', '子任务失败后的最大重试次数', 2, 0, 10),
  'orch.maxLaneIterations': orchNumber('orch.maxLaneIterations', 'Lane 迭代上限', '每个 Lane 的最大迭代次数', 8, 1, 50),
  'orch.maxSubagentIterations': orchNumber('orch.maxSubagentIterations', '子代理迭代上限', '每个子代理的 ReAct 迭代预算', 6, 1, 50),
  'orch.maxAggregateChars': orchNumber('orch.maxAggregateChars', '聚合结果上限', '编排聚合结果字符上限', 122880, 1024, 1048576),
  'orch.maxSubagentResultChars': orchNumber('orch.maxSubagentResultChars', '单结果截断上限', '每个子代理结果字符上限', 51200, 1024, 524288),
  'orch.runTokenBudget': orchNumber('orch.runTokenBudget', 'Run token 预算', '单个 Run token 上限，0 表示不限', 0, 0),
  'orch.runWallClockLimitMinutes': orchNumber('orch.runWallClockLimitMinutes', 'Run 墙钟上限', '单个 Run 时间上限，0 表示不限', 0, 0),
  'orch.subagentTaskTimeoutS': orchNumber('orch.subagentTaskTimeoutS', '单子任务超时', '子任务超时秒数，0 表示不限', 900, 0),
  'orch.maxRetryOfChains': orchNumber('orch.maxRetryOfChains', '重派链上限', 'retry_of 链式重派上限', 10, 1, 100),
  'orch.subagentApprovalMode': enumSetting(
    'orch.subagentApprovalMode',
    '子代理自动批准',
    'ask 逐次审批；auto 自动批准非危险工具',
    'app_settings',
    'ask',
    [
      { value: 'ask', label: '逐次审批' },
      { value: 'auto', label: '自动批准非危险工具' },
    ],
    'next-run',
  ),
  'orch.worktreeIsolation': booleanSetting(
    'orch.worktreeIsolation',
    '子任务 git worktree 隔离',
    '每个子任务在临时 worktree 中工作',
    'app_settings',
    false,
    'next-run',
    'advanced',
  ),
  'orch.scratchRoot': {
    key: 'orch.scratchRoot',
    label: 'Scratch 根目录名',
    description: '子任务 scratch 目录名，仅限单层目录名',
    scope: 'global',
    storage: 'app_settings',
    storageKey: 'orch.scratchRoot',
    defaultValue: 'orch_scratch',
    applyMode: 'next-run',
    visibility: 'advanced',
    riskLevel: 'low',
    constraints: { type: 'string', pattern: '^[a-zA-Z0-9_-]+$' },
  },

  'updates.updateStrategy': enumSetting(
    'updates.updateStrategy',
    '更新策略',
    '手动检查、自动下载或自动安装',
    'electron',
    'auto-download',
    [
      { value: 'manual', label: '手动检查' },
      { value: 'auto-download', label: '自动下载' },
      { value: 'auto-install', label: '自动安装' },
    ],
  ),
  'updates.channel': enumSetting(
    'updates.channel',
    '更新通道',
    'stable 稳定版、beta 测试版或 alpha 预览版',
    'electron',
    'stable',
    [
      { value: 'stable', label: '稳定版' },
      { value: 'beta', label: '测试版' },
      { value: 'alpha', label: '预览版' },
    ],
  ),
  'updates.rollbackWindowDays': numberSetting('updates.rollbackWindowDays', '回滚窗口天数', '安装后允许回滚的天数', 'electron', 7, 1, 30),
  'updates.autoRollbackThreshold': numberSetting('updates.autoRollbackThreshold', '自动回滚触发次数', '启动失败多少次后自动回滚', 'electron', 3, 1, 10),
  'updates.checkIntervalHours': numberSetting('updates.checkIntervalHours', '自动检查周期', '自动检查更新的间隔小时数', 'electron', 24, 1, 168),
  'updates.updateServerUrl': {
    key: 'updates.updateServerUrl',
    label: '更新服务器地址',
    description: '检查更新的服务器地址，必须使用 HTTPS',
    scope: 'global',
    storage: 'electron',
    defaultValue: 'https://updates.sage.app',
    applyMode: 'immediate',
    visibility: 'advanced',
    riskLevel: 'high',
    constraints: { type: 'string', pattern: '^https://' },
  },
  'updates.enableTelemetry': booleanSetting(
    'updates.enableTelemetry',
    '启用更新遥测',
    '是否发送更新相关遥测数据',
    'electron',
    false,
    'immediate',
    'advanced',
  ),
  'updates.cacheRetentionDays': numberSetting('updates.cacheRetentionDays', '缓存保留天数', '更新包缓存保留天数', 'electron', 30, 1, 365),
  closeToTray: booleanSetting(
    'closeToTray',
    '关闭时隐藏到托盘',
    '关闭按钮隐藏到系统托盘而非退出',
    'electron',
    false,
  ),
  'sage:settings-tab': {
    key: 'sage:settings-tab',
    label: '上次访问的设置 Tab',
    description: '记住上次访问的设置 Tab',
    scope: 'global',
    storage: 'local',
    defaultValue: 'general',
    applyMode: 'immediate',
    visibility: 'internal',
    riskLevel: 'low',
    constraints: { type: 'string' },
  },
  'sage:chat-attachment-rag': {
    key: 'sage:chat-attachment-rag',
    label: '超长文档检索注入',
    description: '文档超过 10 万字符时按相关度检索注入',
    scope: 'global',
    storage: 'local',
    defaultValue: { enabled: false, embed: { base_url: '', api_key: '', model: '', dim: 1536 }, top_k: 6 },
    applyMode: 'save-only',
    visibility: 'advanced',
    riskLevel: 'low',
    constraints: { type: 'json' },
  },
};

export function getSettingMetadata(key: string): SettingMetadata | undefined {
  return settingsRegistry[key];
}

export function getAllSettingKeys(): string[] {
  return Object.keys(settingsRegistry);
}

export function getSettingsByVisibility(
  visibility: SettingMetadata['visibility'],
): SettingMetadata[] {
  return Object.values(settingsRegistry).filter((metadata) => metadata.visibility === visibility);
}

export function getSettingsByStorage(
  storage: SettingMetadata['storage'],
): SettingMetadata[] {
  return Object.values(settingsRegistry).filter((metadata) => metadata.storage === storage);
}

export function getSettingsByApplyMode(
  applyMode: SettingMetadata['applyMode'],
): SettingMetadata[] {
  return Object.values(settingsRegistry).filter((metadata) => metadata.applyMode === applyMode);
}
