"""CRUD operations for the skill_drafts table.

SkillDraftStore persists skill drafts generated by the Background Review
pipeline (Task 5) and exposes status-transition helpers for downstream
review workflows.
"""
import json
import sqlite3
import time
from typing import List, Optional

from backend.skills.review_service import SkillDraft


class SkillDraftStore:
    """Thin wrapper around the ``skill_drafts`` SQLite table.

    The table is created by :func:`backend.data.database.init_db`;
    this class assumes it already exists.
    """

    def __init__(self, db_path: str) -> None:
        self.db_path = db_path

    # ── write ─────────────────────────────────────────────────

    def insert(self, draft: SkillDraft) -> None:
        """Insert a new skill draft into the table."""
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """INSERT INTO skill_drafts
                   (id, name, description, when_to_use, content, trigger_type,
                    source_session_id, source_context, status, created_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    draft.id,
                    draft.name,
                    draft.description,
                    draft.when_to_use,
                    draft.content,
                    draft.trigger_type,
                    draft.source_session_id,
                    json.dumps(draft.source_context),
                    draft.status,
                    draft.created_at,
                ),
            )

    def update_status(
        self,
        draft_id: str,
        status: str,
        reviewed_by: Optional[str] = None,
    ) -> None:
        """Transition a draft's status and record review metadata.

        Sets ``reviewed_at`` to the current time (millisecond epoch) and
        optionally records *reviewed_by* in ``reviewed_by_user_id``.
        """
        with sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """UPDATE skill_drafts
                   SET status = ?,
                       reviewed_at = ?,
                       reviewed_by_user_id = ?
                   WHERE id = ?""",
                (status, int(time.time() * 1000), reviewed_by, draft_id),
            )

    # ── read ──────────────────────────────────────────────────

    def get(self, draft_id: str) -> Optional[SkillDraft]:
        """Return a single draft by ID, or ``None`` if not found."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                """SELECT id, name, description, when_to_use, content,
                          trigger_type, source_session_id, source_context,
                          status, created_at
                   FROM skill_drafts
                   WHERE id = ?""",
                (draft_id,),
            )
            row = cursor.fetchone()
            if row is None:
                return None
            return self._row_to_draft(row)

    def list(self, status: str = "pending") -> List[SkillDraft]:
        """Return all drafts matching *status*, newest first."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.execute(
                """SELECT id, name, description, when_to_use, content,
                          trigger_type, source_session_id, source_context,
                          status, created_at
                   FROM skill_drafts
                   WHERE status = ?
                   ORDER BY created_at DESC""",
                (status,),
            )
            return [self._row_to_draft(row) for row in cursor.fetchall()]

    # ── internal ──────────────────────────────────────────────

    @staticmethod
    def _row_to_draft(row: tuple) -> SkillDraft:
        """Deserialise a database row into a :class:`SkillDraft`."""
        (
            id_,
            name,
            description,
            when_to_use,
            content,
            trigger_type,
            source_session_id,
            source_context_json,
            status,
            created_at,
        ) = row

        return SkillDraft(
            id=id_,
            name=name,
            description=description,
            when_to_use=when_to_use,
            content=content,
            trigger_type=trigger_type,
            source_session_id=source_session_id,
            source_context=json.loads(source_context_json),
            status=status,
            created_at=created_at,
        )
